### ISSUE TITLE
[BUG]I encountered an error message

### ISSUE THREAD

**Issue by taotecode** [realodix/urlhub#988]
**Describe the bug**
Call to a member function prepare() on null

**To Reproduce**
1. [First Step]

php artisan migrate --seed
![image](https://github.com/realodix/urlhub/assets/48904825/e3ae2414-b873-4947-be6c-625a241f3879)

![image](https://github.com/realodix/urlhub/assets/48904825/020ca91b-f8f0-42ec-a188-591bef7b3261)
![image](https://github.com/realodix/urlhub/assets/48904825/3cfc319a-bded-4dd9-a38f-7361941914bd)

**Comment by realodix** [comment]
I found the error occurs when the database table does not exist and the table is created while running `php artisan migrate`.

When the table already exists, there is no error.

I can't be sure if the bug comes from UrlHub, Laravel or spatie/laravel-permission.

---

Solution 1 (.env `CACHE_STORE=database`) 

Comment this code

https://github.com/realodix/urlhub/blob/ae5956de05b168042101cf1995b7e8390045ca04/database/migrations/2018_09_04_124737_create_permission_tables.php#L126-L128

Solution 2

In your .env file

```diff
- CACHE_STORE=database
+ CACHE_STORE=file
```

**Comment by taotecode** [comment]
okey

Kei ***@***.***>于2024年5月24日 周五03:06写道：
